const fs=require("fs");
const path=require("path");
const routerinfo=require("./routerinfo");
module.exports={	
	"nd":function(req,res,filename){
		/*
		let basename = path.basename(filename,".nd");		
		routerinfo[basename](req,res);		
        */
		routerinfo[path.basename(filename,".nd")](req,res);
	},
    "html":function(req,res,filename){
        res.statusCode=200;
        res.setHeader("Content-type","text/html;charset=utf-8");
        fs.readFile("front/"+filename,(error,data)=>{
            if(error){
                res.write(error);
                res.end();
            }else{
                res.write(data);
                res.end();
            }
        })
    },
	"css":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","text/css;charset=utf-8");
		fs.readFile("front/"+filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data);
				res.end();
			}
		});
	},
	"jpg":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","binary","image/jpeg");
		fs.readFile("front/"+filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data,"binary");
				res.end();
			}
		});
	},
	"png":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","binary","image/png");
		fs.readFile("front/"+filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data,"binary");
				res.end();
			}
		});
	},
	"gif":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","binary","image/gif");
		fs.readFile("front/"+filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data,"binary");
				res.end();
			}
		});
	},
	"ico":function(req,res,filename){
		res.statusCode=200;
		res.setHeader("Content-type","binary","image/x-icon");
		fs.readFile("front/"+filename,(err,data)=>{
			if(err){
				res.write(err);
				res.end();
			}else{
				res.write(data,"binary");
				res.end();
			}
		});
	},
    "js":function(req,res,filename){
        res.statusCode=200;
        res.setHeader("Content-type","application/x-javascript;charset=utf-8");
        fs.readFile("front/"+filename,(error,data)=>{
            if(error){
                res.write(error);
                res.end();
            }else{
                res.write(data);
                res.end();
            }
        })
    },
    "error":function(req,res){
        res.statusCode=404;
        res.setHeader("Content-type","text/html;charset=utf-8");
            res.write("出错了");
            res.end();
    }
}